// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvv0GnUjD2krlDi-BAI3Q7G-NqXysxl_k',
    appId: '1:936767102059:web:43ad211de6cb9e85baa52e',
    messagingSenderId: '936767102059',
    projectId: 'studentportal-ce718',
    authDomain: 'studentportal-ce718.firebaseapp.com',
    storageBucket: 'studentportal-ce718.firebasestorage.app',
    measurementId: 'G-MTQ4T2W16C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD7Iwa6MaDKvwlRH5i-Ay7SlJAF8kwngI',
    appId: '1:936767102059:android:ce2bffafe545de3dbaa52e',
    messagingSenderId: '936767102059',
    projectId: 'studentportal-ce718',
    storageBucket: 'studentportal-ce718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WAGplzgwm25i8YYSSOKqcNz3nkLCquA',
    appId: '1:936767102059:ios:2e1e89217cd1cd42baa52e',
    messagingSenderId: '936767102059',
    projectId: 'studentportal-ce718',
    storageBucket: 'studentportal-ce718.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WAGplzgwm25i8YYSSOKqcNz3nkLCquA',
    appId: '1:936767102059:ios:2e1e89217cd1cd42baa52e',
    messagingSenderId: '936767102059',
    projectId: 'studentportal-ce718',
    storageBucket: 'studentportal-ce718.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvv0GnUjD2krlDi-BAI3Q7G-NqXysxl_k',
    appId: '1:936767102059:web:f726abaa617361a9baa52e',
    messagingSenderId: '936767102059',
    projectId: 'studentportal-ce718',
    authDomain: 'studentportal-ce718.firebaseapp.com',
    storageBucket: 'studentportal-ce718.firebasestorage.app',
    measurementId: 'G-J45PG6DT5J',
  );
}
